sudo: required
services:
  - docker

before_install:
  - docker-compose up -d

script:
  - docker-compose exec website py.test project/test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY

  secret_access_key:
    secure: "$AWS_SECRET_KEY"

  region: "us-east-2"
  app: "docker-travis"
  env: "DockerTravis-env"
  bucket_name: "elasticbeanstalk-us-east-2-932745336105"
  bucket_path: "docker-travis"
  on:
    repo: Jayden-Liang/docker-travis-aws
