sudo: required
services:
  - docker

before_install:
  - docker-compose up -d

script:
  - docker-compose exec website py.test project/test

before_deploy: "echo 'ready?'"
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: "docker-travis-aws"
  env: "DockerTravisAws-env"
  bucket_name: "elasticbeanstalk-us-east-2-932745336105"
  bucket_path: "docker-travis-aws"
  on:
    branch: master
  access_key_id:$AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
