deploy:
  provider: elasticbeanstalk
  access_key_id: AKIA5SK7UKUUW3QN57LJ
  secret_access_key:
    secure: tQXEMCCTw+81UDW+8lsNdmrUtP4PCpCYURTz/eKoPg/H+0AWqkO3PpsMImSssy+emAaO5jVeiuKKicY/1EHntnxdtucpinT3O4NvoQ3BnDlrvT8ADl97ySTRhXyO2sYdNcrAn5F2KbIo017ccXmOSJiLN65vu2dYlvXDPzfR974t4KOrgNgDymw6CRI2lzUdZX/oH/DHdvDEELtpllneRfz9ypVHoZ/ELEYIZ0dv0vM/hkSURmfgXE9u6oXbW00ufZneBbkgugLASb/97nZGRfGPIuFj4QABBEGSqpVdDDIAPtACKvvdnRug2mxAq2S0Z6u3laxoa6wtb3nS7F80wMi6gb1VF5L62mqltahgG4q38dkrqq8+b3jVY0dTDfZbGLphHghcHLCf6EyNiwnYpSBLMGktaqSGWCDPd6ePB0AUAI50k6djh1mSVysaeV8B3KPoMnKw3zdkzqEMMlcYflbIrEkRNNSU+1jclWjwyWzfK1OZfIf7r0S4HKK0NR7WJBrMNcn+ACwW+YqFTpyxexN+yyN4DlYPsqIlTHu8jQAOKpbZmfJXh+TCF7qfGBh+hjMzsBOq4RhSV7vbCpKZi7ssTxDvG6oVllHW4X9HrBkPV1TcQNz1a6/87zxiypMXCO8qnB5sYOfnALaD9kyyww2M9AbjgA/f2JEy/Wtvv+A=
  region: "us-east-2"
  app: docker-travis-aws
  env: DockerTravisAws-env
  on:
    repo: Jayden-Liang/docker-travis-aws
